clear; close all; clc
textSize = 16;
linewid = 1;


% DP(BM) NLOS 6 7 8 9
% DP(BM) LOS 6 7 8 9
% ED(SA) NLOS 6 7 8 9
% ED(SA) LOS 6 7 8 9
epiImpBMR = [
    1-0.9899796 0 0 0;
    1-0.99442567 0 0 0;
    1-0.998574 1-0.9991554 0 0;
    1-0.999841 1-0.999894 0 0;
    ];

epiImpKMR = [
    1-0.9619565 0 0 0;
    1-0.98378378 0 0 0;
    1-0.9763513 1-0.9898648 0 0;
    1-0.9932432 1-0.9966216 0 0;
    ];
epi = [6, 7, 8, 9];

figure(13);
bar(epi, epiImpBMR', 'grouped')
% plot(epi, epiImpBMRdpn, '-.o', epi, epiImpBMRdpl, '--+', epi, epiImpBMRedn, ':*', epi, epiImpBMRedl, '-.', 'LineWidth', 3)
hold on
ax = gca;
ax.YAxis.FontSize = 13;
ax.XAxis.FontSize = 13;
ax.YAxis.FontWeight = 'bold';
ax.XAxis.FontWeight = 'bold';

ylim([0 0.015])
legend('BM-SKG NLOS', 'BM-SKG LOS', 'SA-SKG NLOS', 'SA-SKG LOS', 'FontSize', textSize, 'FontWeight', 'bold', 'Location', 'northeast')
xlabel('# of Episodes', 'FontSize', 15, 'FontWeight','bold')
ylabel('BMR', 'FontSize',15, 'FontWeight','bold')

% for i=1:length(epiImpBMR)
%     text(epi(i)-0.3,epiImpBMR(1,i),strcat(num2str(epiImpBMR(1,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)-0.1,epiImpBMR(2,i),strcat(num2str(epiImpBMR(2,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.1,epiImpBMR(3,i),strcat(num2str(epiImpBMR(3,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.3,epiImpBMR(4,i),num2str(epiImpBMR(4,i), '%.2g'), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
% end

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.01 /',...
    'Position',[5.7 0.0100204 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0056 /',...
    'Position',[6.04287335129769 0.00563432999999996 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0014 /',...
    'Position',[6.23666146645866 0.00145600000000004 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0002',...
    'Position',[6.38075450290739 0.00015900000000002 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[6.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[6.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0008 /',...
    'Position',[7.1 0.000844599999999973 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0001',...
    'Position',[7.38696638774642 0.00010600000000005 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[7.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[7.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[8.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[8.3 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[8.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[8.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[9.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[9.3 0 0]);

print('losImpBMR','-depsc')


figure(14);
bar(epi, epiImpKMR', 'grouped')
% plot(epi, epiImpKMRdpn, '-.o', epi, epiImpKMRdpl, '--+', epi, epiImpKMRedn, ':*', epi, epiImpKMRedl, '-.', 'LineWidth', 3)
hold on
ax = gca;
ax.YAxis.FontSize = 13;
ax.XAxis.FontSize = 13;
ax.YAxis.FontWeight = 'bold';
ax.XAxis.FontWeight = 'bold';

ylim([0 0.05])
legend('BM-SKG NLOS', 'BM-SKG LOS', 'SA-SKG NLOS', 'SA-SKG LOS', 'FontSize', textSize, 'FontWeight', 'bold', 'Location', 'northeast')
xlabel('# of Episodes', 'FontSize', 15, 'FontWeight','bold')
ylabel('KMR', 'FontSize',15, 'FontWeight','bold')

% for i=1:length(epiImpKMR)
%     text(epi(i)-0.3,epiImpKMR(1,i),strcat(num2str(epiImpKMR(1,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)-0.1,epiImpKMR(2,i),strcat(num2str(epiImpKMR(2,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.1,epiImpKMR(3,i),strcat(num2str(epiImpKMR(3,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.3,epiImpKMR(4,i),num2str(epiImpKMR(4,i), '%.2g'), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
% end

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.038 /',...
    'Position',[5.74893171344784 0.0381435 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.016 /',...
    'Position',[5.9 0.01621622 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.024 /',...
    'Position',[6.1 0.0236487 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0068',...
    'Position',[6.38563049853372 0.00675680000000001 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[6.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[6.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.01 /',...
    'Position',[7.1 0.0101352 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0034',...
    'Position',[7.37339757017176 0.0033784 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[7.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[7.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[8.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[8.3 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[8.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[8.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0 /',...
    'Position',[9.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[9.3 0 0]);
print('losImpKMR','-depsc')