clear; close all; clc
textSize = 16;
linewid = 1;

% ISm-CSI  5 6 7 8
% ISm-RSS 5 6 7 8

epiImpBMR = [
    1-0.9997119816 0 0 0;
    1-0.9999472128 0 0 0;
    ];
epi = [5 6 7 8];

figure(111)
bar(epi, epiImpBMR(1:2,:)', 'grouped')
hold on
ax = gca;
ax.YAxis.FontSize = 14;
ax.XAxis.FontSize = 14;
ax.YAxis.FontWeight = 'bold';
ax.XAxis.FontWeight = 'bold';
ax.LineWidth = 1;
ylim([0 0.001]);
legend('SIM-SKG with CSI', 'SIM-SKG with RSS', 'FontSize',textSize, 'FontWeight','bold', 'Location','northeast')
xlabel('Episode Length', 'FontSize', 15, 'FontWeight','bold')
ylabel('BMR (%)', 'FontSize',15, 'FontWeight','bold')
grid on
% for i=1:length(epiImpBMR)
%     text(epi(i)-0.1,epiImpBMR(1,i),strcat(num2str(epiImpBMR(1,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.1,epiImpBMR(2,i),strcat(num2str(epiImpBMR(2,i), '%.2g')), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
% end

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0.00029 /',...
    'Position',[4.9 0.000288018400000034 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','5.3e-05',...
    'Position',[5.22811059907834 5.27872000000151e-05 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0 /',...
    'Position',[5.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0',...
    'Position',[6.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0 /',...
    'Position',[6.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0',...
    'Position',[7.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0 /',...
    'Position',[7.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0',...
    'Position',[8.1 0 0]);


print('epiCSIBMR','-depsc')

% epiImp = [
%     3*7/5 3*7/6 3*7/7 3*7/8;
%     7/5 7/6 7/7 7/8
%     ];
epiImp = [
    7/5*(1-0.00029) 7/6 7/7 7/8;
    7/5*(1-0.000053) 7/6 7/7 7/8
    ];
epiImp = epiImp.';
figure(113)
bar(epi, epiImp(1:4,:), 'grouped')
hold on
ax = gca;
ax.YAxis.FontSize = 14;
ax.XAxis.FontSize = 14;
ax.YAxis.FontWeight = 'bold';
ax.XAxis.FontWeight = 'bold';
ax.LineWidth = 1;
ylim([0 2.5])
legend('SIM-SKG with CSI', 'SIM-SKG with RSS', 'FontSize',textSize, 'FontWeight','bold', 'Location','northeast')
xlabel('Episode Length', 'FontSize', 15, 'FontWeight','bold')
ylabel('BGR (bit per sample)', 'FontSize',15, 'FontWeight','bold')
grid on

% for i=1:length(epiImp)
%     text(epi(i)-0.15,epiImp(i,1),strcat(num2str(epiImp(i,1), '%.2g'), " /"), 'FontSize',12, 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.15,epiImp(i,2),num2str(epiImp(i,2), '%.2g'), 'FontSize',12, 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
% end

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','1.4 /',...
    'Position',[4.85915075707702 1.399594 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','1.4',...
    'Position',[5.15 1.3999258 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','1.2 /',...
    'Position',[5.85915075707702 1.16666666666667 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','1.2',...
    'Position',[6.15 1.16666666666667 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','1 /',...
    'Position',[6.86830151415405 1 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','1',...
    'Position',[7.15 1 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0.88 /',...
    'Position',[7.84084924292297 0.875 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0.88',...
    'Position',[8.19575378538512 0.875 0]);

print('epiCSIBGR','-depsc')