clear; close all; clc
textSize = 16;
linewid = 1;


% MI 256 384 512 640
% SI 256 384 512 640
% MO 256 384 512 640
% SO 256 384 512 640
kleImpBMR = [
    0 0 0 0 0 0 0; 
    0 0 0 0 0 1-0.9998449901 1-0.9996834783;
    0 0 0 0 1-0.99921875 1-0.998046875 1-0.9838600068; 
    0 0 0 0 0 0 0
   ];
epi = [4, 5, 6, 7, 8, 9, 10];

figure(1)
bar(epi, kleImpBMR(1:4,:)', 'grouped')
hold on
ax = gca;
ax.YAxis.FontSize = 13;
ax.XAxis.FontSize = 13;
ax.YAxis.FontWeight = 'bold';
ax.XAxis.FontWeight = 'bold';
xticklabels({'32','64','128','256','384','512','640'})
ylim([0 0.03])
legend('Mobile Indoor','Stationary Indoor', 'Mobile Outdoor', 'Stationary Outdoor', 'FontSize',textSize, 'FontWeight','bold', 'Location','northeast')
xlabel('# of Episodes', 'FontSize', 15, 'FontWeight','bold')
ylabel('BMR (percent)', 'FontSize',15, 'FontWeight','bold')

% for i=1:length(kleImpBMR)
%     text(epi(i)-0.3,kleImpBMR(1,i),strcat(num2str(kleImpBMR(1,i), '%.2g'),"/"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)-0.1,kleImpBMR(2,i),strcat(num2str(kleImpBMR(2,i), '%.2g'),"/"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.1,kleImpBMR(3,i),strcat(num2str(kleImpBMR(3,i), '%.2g'),"/"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.3,kleImpBMR(4,i),num2str(kleImpBMR(4,i), '%.2g'), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
% end

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[3.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[3.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[4.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[4.3 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[4.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[4.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[5.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[5.3 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[5.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[5.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[6.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[6.3 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[6.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[6.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[7.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[7.3 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[7.7 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[7.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0008',...
    'Position',[7.88760459509289 0.000961249999999955 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[8.3 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[8.68366189193022 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0002',...
    'Position',[8.67126648702312 0.000965009899999947 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.002/',...
    'Position',[9.1 0.001953125 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[9.3 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0/',...
    'Position',[9.68366189193022 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.0003',...
    'Position',[9.65492837895334 0.00094652169999996 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.016/',...
    'Position',[10.1 0.0161399932 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0',...
    'Position',[10.3 0 0]);

print('kleImpBMRLa','-depsc')