clear; close all; clc
textSize = 16;
linewid = 1;

% NLOS 5 6 7 8
% LOS 5 6 7 8
epiImpBMR = [
    1-0.9990890888 1-0.9999308628 0 0;
    0.00014 0 0 0;
    ];

% epiImpKMR = [
%     1-0.9619565 0 0 0;
%     1-0.98378378 0 0 0;
%     ];
epi = [5, 6, 7, 8];

figure(13);
bar(epi, epiImpBMR', 'grouped')
% plot(epi, epiImpBMRdpn, '-.o', epi, epiImpBMRdpl, '--+', epi, epiImpBMRedn, ':*', epi, epiImpBMRedl, '-.', 'LineWidth', 3)
hold on
ax = gca;
ax.YAxis.FontSize = 14;
ax.XAxis.FontSize = 14;
ax.YAxis.FontWeight = 'bold';
ax.XAxis.FontWeight = 'bold';
ax.LineWidth = 1;
ylim([0 0.002])
legend('NLOS', 'LOS', 'FontSize', textSize, 'FontWeight', 'bold', 'Location', 'northeast')
xlabel('Episode Length', 'FontSize', 15, 'FontWeight','bold')
ylabel('BMR', 'FontSize',15, 'FontWeight','bold')
grid on
% for i=1:length(epiImpBMR)
%     text(epi(i)-0.1,epiImpBMR(1,i),strcat(num2str(epiImpBMR(1,i), '%.2g')," /"), 'FontSize',12, 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.1,epiImpBMR(2,i),num2str(epiImpBMR(2,i), '%.2g'), 'FontSize',12, 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
% end

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0.00091 /',...
    'Position',[4.9 0.000910911199999975 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0.00014',...
    'Position',[5.25556287030941 0.00014 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','6.9e-05 /',...
    'Position',[5.89084924292298 8.12096346076593e-05 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0',...
    'Position',[6.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0 /',...
    'Position',[6.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0',...
    'Position',[7.1 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0 /',...
    'Position',[7.9 0 0]);

% 创建 text
text('VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',12,...
    'String','0',...
    'Position',[8.1 0 0]);

print('losImpBMR','-depsc')

% figure(14);
% bar(epi, epiImpKMR', 'grouped')
% % plot(epi, epiImpKMRdpn, '-.o', epi, epiImpKMRdpl, '--+', epi, epiImpKMRedn, ':*', epi, epiImpKMRedl, '-.', 'LineWidth', 3)
% hold on
% ax = gca;
% ax.YAxis.FontSize = 13;
% ax.XAxis.FontSize = 13;
% ax.YAxis.FontWeight = 'bold';
% ax.XAxis.FontWeight = 'bold';
% 
% ylim([0 0.05])
% legend('BM-SKG NLOS', 'BM-SKG LOS', 'SA-SKG NLOS', 'SA-SKG LOS', 'FontSize', textSize, 'FontWeight', 'bold', 'Location', 'northeast')
% xlabel('# of Episodes', 'FontSize', 15, 'FontWeight','bold')
% ylabel('KMR', 'FontSize',15, 'FontWeight','bold')

% for i=1:length(epiImpKMR)
%     text(epi(i)-0.3,epiImpKMR(1,i),strcat(num2str(epiImpKMR(1,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)-0.1,epiImpKMR(2,i),strcat(num2str(epiImpKMR(2,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.1,epiImpKMR(3,i),strcat(num2str(epiImpKMR(3,i), '%.2g')," /"), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
%     text(epi(i)+0.3,epiImpKMR(4,i),num2str(epiImpKMR(4,i), '%.2g'), 'FontWeight','bold', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom')
% end

% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0.038 /',...
%     'Position',[5.74893171344784 0.0381435 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0.016 /',...
%     'Position',[5.9 0.01621622 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0.024 /',...
%     'Position',[6.1 0.0236487 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0.0068',...
%     'Position',[6.38563049853372 0.00675680000000001 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0 /',...
%     'Position',[6.7 0 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0 /',...
%     'Position',[6.9 0 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0.01 /',...
%     'Position',[7.1 0.0101352 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0.0034',...
%     'Position',[7.37339757017176 0.0033784 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0 /',...
%     'Position',[7.7 0 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0 /',...
%     'Position',[7.9 0 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0 /',...
%     'Position',[8.1 0 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0',...
%     'Position',[8.3 0 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0 /',...
%     'Position',[8.7 0 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0 /',...
%     'Position',[8.9 0 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0 /',...
%     'Position',[9.1 0 0]);
% 
% % 创建 text
% text('VerticalAlignment','bottom',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'String','0',...
%     'Position',[9.3 0 0]);
% print('losImpKMR','-depsc')